### ISSUE TITLE
Error serialize method

### ISSUE THREAD

**Issue by StefanoPaparesta** [rjperes/EFAuditable#2] opened 2024-11-29 06:00 UTC
When save changes i catch this error in method 

public string Serialize(object entity, params string[] ignoreProperties)

System.Text.Json.JsonException: 'A possible object cycle was detected. This can either be due to a cycle or if the object depth is larger than the maximum allowed depth of 2. Consider using ReferenceHandler.Preserve on JsonSerializerOptions to support cycles. Path: $.Properties.'

**Comment by rjperes** [comment] 2024-11-29 07:37
Thanks, what does your entity look like?

**Comment by StefanoPaparesta** [comment] 2024-11-29 07:47
I'm using the test program console, the error  is in the key serialization

**Comment by rjperes** [comment] 2024-11-29 07:53
I'm sorry, but I don't get that error. Even added a relation, and it still works fine.

**Comment by rjperes** [comment] 2024-11-30 11:03
Closing as cannot reproduce

**Closed as completed by rjperes** 2024-11-30 11:03 UTC
Labels: bug
